### PR TITLE
Update config.yml

### PR DESCRIPTION
**Pull request by rahulmahendru**

### CODE REVIEW

**Comment by nahtnam** [comment]
We use npm instead of yarn

**Review by nahtnam — CHANGES_REQUESTED** [review]
Additionally, the test is failing. Do me a favor and add this to the .eslint file

```
"jsx-a11y/anchor-is-valid": 0,
"jsx-a11y/aria-role": 0
```

That should fix it. Also stop making multiple PRs. If you commit and push to your branch, it will automatically add it to this PR

**Comment by rahulmahendru** [comment]
Used npm instead of yarn. Also, the .eslint file already has those statements.

**Comment by rahulmahendru** [comment]
Update to build for linux

**Review by nahtnam — APPROVED** [review]

**Pull request merged**
